spring:
  application:
    name: TrainTicketBooking


#  security:
#    user:
#      name: user
#      password: "{noop}user"  # {noop} means no encoding
#

  datasource:
    url: jdbc:mysql://localhost:3306/trainticketbooking
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

management:
  endpoint:
    web:
      exposure:
        include:*

    health:
      show-details:always


server:
  port : 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG